name: Create and publish terraform-aws-cli Docker image

on:
  # schedule:
  #   - cron:  '0 17 * * *' 
  # workflow_call:
  push:
    branches: ${{ github.ref_name }} 
    paths:
      - 'docker_images/terraform-aws-cli/**'
      - '.github/workflows/build_terraform-aws-cli.yml'  

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/apcupsd  
  PROJECT_NAME: terraform-aws-cli  
  DOCKER_FROM: 'alpine'
  GIT_BRANCH: ${{ github.ref_name }}

jobs:
  build-and-push-image:
    if: ${{ always() }}
    needs: [check-latest-version, check-image-version]
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.DOCKER_FROM }}
            ${{ env.GIT_BRANCH }}
            # ${{ env.APCUPSD_CURRENT_VERSION }}
            # set latest tag for main branch
            type=raw,value=latest,enable={{is_default_branch}} 
          labels: |
            # base_image=${{ env.DOCKER_FROM }}
            org.opencontainers.image.url=https://github.com/${{ env.IMAGE_NAME }}
            org.opencontainers.image.source=https://github.com/${{ env.IMAGE_NAME }}
            # apcupsd_version=${{ env.APCUPSD_CURRENT_VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@master 
        with:
          platforms: linux/amd64,linux/arm64
          context: "{{defaultContext}}:terraform-aws-cli"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
 